import type { SupportedDialect } from '../sql/datasource.types';

export const ACTIVITY_LOG_MIGRATIONS: Record<SupportedDialect, string> = {
  postgres: `
    CREATE TABLE IF NOT EXISTS activity_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      log_name VARCHAR(255) NOT NULL,
      description TEXT NOT NULL,
      subject_type VARCHAR(255),
      subject_id VARCHAR(255),
      causer_type VARCHAR(255),
      causer_id VARCHAR(255),
      event VARCHAR(255),
      properties JSONB NOT NULL,
      batch_uuid VARCHAR(255),
      created_at TIMESTAMPTZ(3) NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_activity_log_log_name ON activity_log (log_name);
    CREATE INDEX IF NOT EXISTS idx_activity_log_subject ON activity_log (subject_type, subject_id);
    CREATE INDEX IF NOT EXISTS idx_activity_log_causer ON activity_log (causer_type, causer_id);
  `,
  mysql: `
    CREATE TABLE IF NOT EXISTS activity_log (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
      log_name VARCHAR(255) NOT NULL,
      description TEXT NOT NULL,
      subject_type VARCHAR(255) NULL,
      subject_id VARCHAR(255) NULL,
      causer_type VARCHAR(255) NULL,
      causer_id VARCHAR(255) NULL,
      event VARCHAR(255) NULL,
      properties JSON NOT NULL,
      batch_uuid VARCHAR(255) NULL,
      created_at DATETIME(3) NOT NULL,
      INDEX idx_activity_log_log_name (log_name),
      INDEX idx_activity_log_subject (subject_type, subject_id),
      INDEX idx_activity_log_causer (causer_type, causer_id)
    );
  `,
  sqlite: `
    CREATE TABLE IF NOT EXISTS activity_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      log_name TEXT NOT NULL,
      description TEXT NOT NULL,
      subject_type TEXT,
      subject_id TEXT,
      causer_type TEXT,
      causer_id TEXT,
      event TEXT,
      properties TEXT NOT NULL,
      batch_uuid TEXT,
      created_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_activity_log_log_name ON activity_log (log_name);
    CREATE INDEX IF NOT EXISTS idx_activity_log_subject ON activity_log (subject_type, subject_id);
    CREATE INDEX IF NOT EXISTS idx_activity_log_causer ON activity_log (causer_type, causer_id);
  `,
};
